import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "../components/layout/auth-provider";
import { RegisterFormStoreProvider } from "../providers/register-form-store-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className="antialiased">
        <RegisterFormStoreProvider>
          <AuthProvider>{children}</AuthProvider>
        </RegisterFormStoreProvider>
      </body>
    </html>
  );
}
