# Generated by Django 5.2 on 2026-05-26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0007_alter_ticket_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        choices=[
                            ("PENDING_REVIEW", "Принята на рассмотрение"),
                            ("IN_PROGRESS", "Работы ведутся"),
                            ("COMPLETED", "Работы завершены"),
                            ("REJECTED", "Отказано"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("PENDING_REVIEW", "Принята на рассмотрение"),
                            ("IN_PROGRESS", "Работы ведутся"),
                            ("COMPLETED", "Работы завершены"),
                            ("REJECTED", "Отказано"),
                        ],
                        max_length=20,
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий оператора")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="tickets.ticket",
                        verbose_name="Заявка",
                    ),
                ),
            ],
            options={
                "verbose_name": "История статуса заявки",
                "verbose_name_plural": "История статусов заявок",
                "ordering": ["-created_at"],
            },
        ),
    ]
